name: gr1_shield
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - atk-1.0=2.36.0=h3371d22_4
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.16.0=h6cf1ce9_1008
  - expat=2.7.1=h6a678d5_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.13.1=h6c09931_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - gdk-pixbuf=2.42.6=h04a7f16_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - giflib=5.2.2=hd590300_0
  - graphite2=1.3.14=hecca717_2
  - graphviz=2.49.0=h85b4f2f_0
  - gtk2=2.24.33=h539f30e_1
  - gts=0.7.6=h64030ff_2
  - harfbuzz=3.0.0=h83ec7ef_1
  - icu=68.2=h9c3ff4c_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h0b41bf4_3
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=2.2.1=h9c3ff4c_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libdeflate=1.7=h7f98852_5
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgd=2.3.3=h6ad9fb6_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libglib=2.68.4=h174f98d_1
  - libgomp=15.1.0=h767d61c_4
  - libiconv=1.18=h3b78370_2
  - libltdl=2.4.3a=h5888daf_0
  - libpng=1.6.39=h5eee18b_0
  - librsvg=2.52.2=hc3c00ef_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.3.0=hf544144_1
  - libtool=2.5.4=h5888daf_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=hd590300_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.9.12=h72842e0_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - ncurses=6.5=h7934f7d_0
  - openssl=3.5.2=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.48.10=h54213e6_2
  - pcre=8.45=h9c3ff4c_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - python_abi=3.10=2_cp310
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - spot=2.14.1=py310hf71b8c6_1
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.0=ha95c52a_0
  - pip:
      - altgraph==0.17.4
      - jpype1==1.6.0
      - modulegraph==0.19.6
      - numpy==2.2.6
      - pandas==2.3.2
      - py-ltl==0.1.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - six==1.17.0
      - tzdata==2025.2
prefix: /home/sacktock/anaconda3/envs/gr1_shield
